development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:195fc78167cc6164c7d35a49cfd60a16@tarpon.redistogo.com:10733/
  channel_prefix: talkomatic2_production
