development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: ENV['REDISGO_URL']
  channel_prefix: talkomatic2_production
  host: tarpon.redistogo.com
  port: 10733
  password: ENV['REDISGO_PASSWORD']
